name: bench

on:
  schedule:
    - cron: 0 12 * * *
  workflow_dispatch:

jobs:
  bench:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install bombardier
        run: go install github.com/codesenberg/bombardier@latest

      - name: Install Dependencies
        uses: npm ci

      - name: Run Benchmark
        run: deno run -A bench.js
